name: linter

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: install golangci-lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.23.6
    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run --new-from-rev origin/HEAD ./...
